#! /usr/bin/python

import requests
import json
import sys

if(len(sys.argv) > 1):

	searchTerm = "define " + "".join(sys.argv[1:])

	payload = {'q':searchTerm, 'o':'json'}
	r = requests.get('http://www.duckduckgo.com/', params=payload)
	
	resultJson = json.loads(r.text)

	print resultJson["AbstractText"];

